### PR TITLE
Donations banner

### LINKED ISSUE #607: replace the Tweets section with a call for donations
Following planningalerts on twitter is a way to stay up-to-date date with new authorities being added, promotions of other civic tech activities and down time to the application. Not many people follow the account currently, and we know that many people using PlanningAlerts aren't interested in civic tech more widely. Twitter is a good way for people to contact OAF about broken scrapers or ask questions, but the contact or about page would be a more logical place to look for this.

This section could instead feature a sentence explaining that the site is independent and charity run and call on people who find it useful to donate—contributing to the improvement of the service and becoming more connected to it. This gives citizens more information about how the project works, putting them in a better position to support the project if they find it useful (a number of users have said they thought the project was supported by councils/government).

### LINKED ISSUE #611: replace front page news section with twitter feed
The news section is not being updated and gives the impression that the sight isn't under current development or that the managers are elsewhere (this is not the case :) ) . The twitter feed is where information about updates to the site are, it would better accomplish the apparent aims of this section than the out of date news feed.

This comes from discussion on #607 and PR #610 :

> However, I'd like to replace the "News" section with items from the Twitter feed instead of the blog since it's so rarely updated - the latest entry is from over a year ago! At least the twitter feed is a bit more current.
— @henare 

* [x] fix the twitter feed so that it successfully gets tweets
* [x] make changes to it fits in the news section.

### PR DESCRIPTION
**Pull request by equivalentideas**
To increase small donations from the project's citizens, include them and give them a sense of ownership of the project, this PR removes the inclusion of the twitter banner and replaces it with a new, bright banner that calls on users to 'chip in to support PlanningAlerts'.

@mlandauer could merge this or give some feedback :) see the discussion on the issue about your earlier [comment](https://github.com/openaustralia/planningalerts-app/issues/607#issuecomment-71128798)

Here's what it looks like:

screen shot 2015-01-23 at 4 24 15 pm
screen shot 2015-01-23 at 4 17 14 pm

closes #607
closes #611

### CODE REVIEW

**Comment by equivalentideas** [comment]
I've also just made two commits (https://github.com/equivalentideas/planningalerts-app/commit/5b4fb92cced2a94a3ac0eea0bf62d2ec68696baf and  https://github.com/equivalentideas/planningalerts-app/commit/6ddb191d90ff861b9493d12635fa7e49ef4838ee) to remove the Twitter helper, model, initialiser and partials supporting the feed removed in this PR. They can be reverted if we want to use the twitter feed, but as @henare says "clean up and don't plan for the future".

**Comment by henare** [comment]
We discussed at lunch that this can be merged once it also addresses #611.

**Comment by equivalentideas** [comment]
I've replaced the news section with the tweeter feed (#611):

screen shot 2015-02-16 at 12 09 35 pm

I'd like to introduce this as an AB test to see what impact changing the news section for the twitter feed has, and to see if the donations banner does succeed to getting more people to the oaf.org.au/donate page.

Is there additional code I need to add (feature flag?) to run an AB test? @henare @mlandauer

**Comment by mlandauer** [comment]
There's two separate things here:
* Replacing the news section for the twitter feed
* Adding the donate banner

For the first, what would you actually be testing? Is there a measure of success?
For the second, we could run it as an A/B test but I wonder if it's worth the added complexity. We're adding a new source of donation links so we could just see if new donations are coming via those links. If they're not we revert this feature.

It would be good @equivalentideas to get you up to speed with the A/B testing framework on PlanningAlerts but it would slow down the merging of this PR which has been hanging around too long I think. How about we do A/B testing the next time it comes up?

**Comment by equivalentideas** [comment]
> How about we do A/B testing the next time it comes up?

Ok cool, that makes sense.

With the first bit:

> Replacing the news section for the twitter feed

I was interested to see how it impacts new alert subscriptions though the home page. But I can somewhat observe that from the analytics. We'll probably be doing some AB at some point down the track so I can learn how to run it then.

I'm happy with that @mlandauer if you want to merge this :+1:

**Comment by mlandauer** [comment]
@equivalentideas before I merge this, did you check that this PR doesn't break anything on the NSW theme?

**Comment by equivalentideas** [comment]
@mlandauer Good thinking! Forgot about that.

**Comment by equivalentideas** [comment]
It did impact the theme and I've fixed that up.

Also I'm cleaning up a left over view partial of _news and the styles for it in the scss.

**Comment by mlandauer** [comment]
Coolio. Let me know when it's ready to merge

**Comment by equivalentideas** [comment]
When tests pass go for it :+1: Thanks!

**Comment by equivalentideas** [comment]
Ready to go @mlandauer

**Pull request merged**
